[package]
name = "epics-ca"
version = "0.1.0"
authors = ["Michael Abbott <michael.abbott@diamond.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
